[tool.poetry]
name = "artem levkin"
version = "0.1.0"
description = ""
authors = ["Artemon3"]

[tool.poetry.dependencies]
python = "^3.11"
build = "^1.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
